# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      run: ./gradlew build bootJar  # Use 'run' to execute the build command
    - name: Syft SBOM generation
      uses: anchore/sbom-action@v0
    - name: Run Trivy in GitHub SBOM mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: fs
        format: github
        output: "build/sbom.trivy.spdx.json"
    - name: Run Microsoft SBOM tool
      run: |
        curl -Lo $RUNNER_TEMP/sbom-tool https://github.com/microsoft/sbom-tool/releases/latest/download/sbom-tool-linux-x64
        chmod +x $RUNNER_TEMP/sbom-tool
        $RUNNER_TEMP/sbom-tool generate -b ./buildOutput -bc . -pn Test -pv 1.0.0 -ps MyCompany -nsb https://sbom.mycompany.com -V Verbose
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: build-artifact
        path: build/libs  # Path to the build output directory
    - name: Upload Trivy SBOM
      uses: actions/upload-artifact@v3.1.0
      with:
        name: trivy-sbom
        path: "build/sbom.trivy.spdx.json"
    - name: Upload Microsoft SBOM
      uses: actions/upload-artifact@v3.1.0
      with:
        name: microsoft-sbom
        path: "buildOutput"

